# -*- coding: utf-8 -*-
"""control_catalog

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6CBWXjwveQALQIuGmHdHJDrNm6JE2aQ
"""

import streamlit as st
import pandas as pd

def render():

    st.markdown("""
        <h2 style='text-align: left; color: #1f4e79;'>
        📚 India AI Governance – Control Catalog
        </h2>
    """, unsafe_allow_html=True)

    # Load Excel
    df = pd.read_excel("data/India_AI_Governance_Framework_Playbook_FINAL_DETAILED.xlsx")

    # Filters
    col1, col2 = st.columns(2)

    with col1:
        stage_filter = st.selectbox(
            "Filter by Lifecycle Stage",
            ["All"] + sorted(df["Lifecycle Stage"].unique())
        )

    with col2:
        risk_filter = st.selectbox(
            "Filter by Risk Level",
            ["All"] + sorted(df["Applicable Risk Level"].unique())
        )

    search = st.text_input("🔍 Search Control Title")

    # Apply filters
    filtered_df = df.copy()

    if stage_filter != "All":
        filtered_df = filtered_df[filtered_df["Lifecycle Stage"] == stage_filter]

    if risk_filter != "All":
        filtered_df = filtered_df[filtered_df["Applicable Risk Level"] == risk_filter]

    if search:
        filtered_df = filtered_df[
            filtered_df["Control Title"].str.contains(search, case=False)
        ]

    st.markdown(f"### Showing {len(filtered_df)} Controls")

    # Display controls
    for index, row in filtered_df.iterrows():
        with st.expander(f"{row['Control ID']} — {row['Control Title']}"):

            st.markdown(f"**Lifecycle Stage:** {row['Lifecycle Stage']}")
            st.markdown(f"**Category:** {row['Control Category']}")
            st.markdown(f"**Risk Level:** {row['Applicable Risk Level']}")
            st.markdown(f"**Responsible Role:** {row['Responsible Role']}")

            st.markdown("### 📝 Control Description")
            st.write(row["Detailed Control Description (~150 words)"])

            st.markdown("### 📘 Regulatory Mapping")
            st.write(row["Detailed Regulatory Mapping"])

            st.markdown("### 🔗 Reference")
            st.markdown("[View DPDP Act](https://www.meity.gov.in/writereaddata/files/DPDP%20Act%202023.pdf)")
            st.markdown("[CERT-In Directions](https://www.cert-in.org.in/)")
            st.markdown("[ISO 42001](https://www.iso.org/standard/81230.html)")