# -*- coding: utf-8 -*-
"""cross_framework_mapping.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBLzLkFPTsJnBNb55hzkasHtGMzM8kUu
"""
import streamlit as st
import pandas as pd


def render():

    st.markdown("""
    <style>
    .framework-card {
        background-color: #ffffff;
        padding: 18px;
        border-radius: 12px;
        box-shadow: 0px 4px 12px rgba(0,0,0,0.05);
        margin-bottom: 15px;
    }

    .india {
        border-left: 6px solid #1f4e79;
    }

    .nist {
        border-left: 6px solid #2ca02c;
    }

    .ucf {
        border-left: 6px solid #ff7f0e;
    }

    .badge {
        font-weight: 600;
        font-size: 14px;
        padding: 4px 10px;
        border-radius: 20px;
        display: inline-block;
        margin-bottom: 8px;
    }

    .india-badge { background-color:#e8f0fe; color:#1f4e79; }
    .nist-badge { background-color:#e6f4ea; color:#2ca02c; }
    .ucf-badge { background-color:#fff3e0; color:#ff7f0e; }

    </style>
    """, unsafe_allow_html=True)

    st.markdown("## 🔗 Cross-Framework Mapping")
    st.markdown("Structured one-to-one mapping between India AI Governance, NIST AI RMF, and Unified Control Framework.")

    # Load mapping file
    df = pd.read_excel(
        "data/India_AI_Cross_Framework_Mapping_Unique_OneToOne.xlsx",
        engine="openpyxl"
    )

    # Dropdown
    selected_control = st.selectbox(
        "Select India AI Governance Control",
        df["India Control ID"]
    )

    row = df[df["India Control ID"] == selected_control].iloc[0]

    st.markdown("---")

    # India Card
    st.markdown(f"""
    <div class="framework-card india">
        <span class="badge india-badge">🇮🇳 India AI Governance</span>
        <h4>{row['India Control ID']}</h4>
        <p><b>Title:</b> {row['India Control Title']}</p>
        <p><b>Lifecycle Stage:</b> {row['Lifecycle Stage']}</p>
    </div>
    """, unsafe_allow_html=True)

    # NIST Card
    st.markdown(f"""
    <div class="framework-card nist">
        <span class="badge nist-badge">🇺🇸 NIST AI RMF</span>
        <h4>{row['Mapped NIST Control']}</h4>
        <p><b>Function:</b> {row['Mapped NIST Function']}</p>
        <p><b>Similarity Score:</b> {row['NIST Similarity Score']}</p>
    </div>
    """, unsafe_allow_html=True)

    # UCF Card
    st.markdown(f"""
    <div class="framework-card ucf">
        <span class="badge ucf-badge">📘 Unified Control Framework</span>
        <h4>{row['Mapped UCF Control']}</h4>
        <p><b>Similarity Score:</b> {row['UCF Control Similarity Score']}</p>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("---")
    st.info("Mapping follows lifecycle-aligned, structured one-to-one assignment without duplication.")
