# -*- coding: utf-8 -*-
"""cross_framework_mapping.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBLzLkFPTsJnBNb55hzkasHtGMzM8kUu
"""

import streamlit as st
import pandas as pd


def render():

    st.markdown("## 🔗 Cross-Framework Control Mapping")

    # Load datasets
    india_df = pd.read_excel(
        "data/India_AI_Governance_Framework_Playbook_FINAL_DETAILED.xlsx",
        engine="openpyxl"
    )

    nist_df = pd.read_csv("data/nist_ai_rmf_playbook.csv")
    ucf_control = pd.read_csv("data/control_library.csv")
    ucf_policy = pd.read_csv("data/policy_requirements.csv")
    ucf_risk = pd.read_csv("data/risk_library.csv")

    # Select India Control
    selected_control = st.selectbox(
        "Select India AI Governance Control",
        india_df["Control ID"] + " — " + india_df["Control Title"]
    )

    control_id = selected_control.split(" — ")[0]

    india_row = india_df[india_df["Control ID"] == control_id].iloc[0]

    st.markdown("### 🇮🇳 India AI Governance Control")
    st.write("**Title:**", india_row["Control Title"])
    st.write("**Lifecycle Stage:**", india_row["Lifecycle Stage"])
    st.write("**Risk Level:**", india_row["Applicable Risk Level"])
    st.write("**Description:**")
    st.write(india_row["Detailed Control Description (~150 words)"])

    # 🔎 SIMPLE KEYWORD MATCHING
    keywords = india_row["Control Title"].lower().split()

    def keyword_filter(df, column):
        return df[df[column].str.lower().apply(
            lambda x: any(word in x for word in keywords)
        )]

    # NIST Mapping
    st.markdown("---")
    st.markdown("### 🇺🇸 Mapped NIST AI RMF Controls")

    if "Control Title" in nist_df.columns:
        nist_matches = keyword_filter(nist_df, "Control Title")
    else:
        nist_matches = nist_df.head(5)

    if len(nist_matches) > 0:
        st.dataframe(nist_matches.head(10))
    else:
        st.info("No direct keyword match found.")

    # UCF Control Library
    st.markdown("### 📘 Unified Control Framework – Control Library")

    if "control_name" in ucf_control.columns:
        ucf_matches = keyword_filter(ucf_control, "control_name")
    else:
        ucf_matches = ucf_control.head(5)

    st.dataframe(ucf_matches.head(10))

    # UCF Policy Requirements
    st.markdown("### 📜 Unified Control Framework – Policy Requirements")

    if "policy_title" in ucf_policy.columns:
        policy_matches = keyword_filter(ucf_policy, "policy_title")
    else:
        policy_matches = ucf_policy.head(5)

    st.dataframe(policy_matches.head(10))

    # UCF Risk Library
    st.markdown("### ⚠ Unified Control Framework – Risk Library")

    if "risk_name" in ucf_risk.columns:
        risk_matches = keyword_filter(ucf_risk, "risk_name")
    else:
        risk_matches = ucf_risk.head(5)

    st.dataframe(risk_matches.head(10))