# -*- coding: utf-8 -*-
"""downloads

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6CBWXjwveQALQIuGmHdHJDrNm6JE2aQ
"""

import streamlit as st

def render():
    st.header("📥 Download Artifacts")

    with open("templates/ai_inventory_template.csv", "rb") as f:
        st.download_button("Download AI Inventory Template", f, "ai_inventory_template.csv")

    with open("templates/aibom_template.csv", "rb") as f:
        st.download_button("Download AIBOM Template", f, "aibom_template.csv")