# -*- coding: utf-8 -*-
"""evaluate

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6CBWXjwveQALQIuGmHdHJDrNm6JE2aQ
"""

import streamlit as st

def render():
    st.header("🧪 Evaluate")

    safety = st.slider("Safety", 0, 100, 80)
    privacy = st.slider("Privacy", 0, 100, 85)
    fairness = st.slider("Fairness", 0, 100, 75)

    if min([safety, privacy, fairness]) < 70:
        st.error("Evaluation Gate Failed")
    else:
        st.success("Evaluation Gate Passed")