# -*- coding: utf-8 -*-
"""monitor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6CBWXjwveQALQIuGmHdHJDrNm6JE2aQ
"""

import streamlit as st

def render():
    st.header("📊 Monitor")

    drift = st.slider("Model Drift Level", 0, 100, 25)
    bias = st.slider("Bias Risk Level", 0, 100, 15)

    if drift > 50:
        st.warning("Drift Detected – Retraining Required")

    if bias > 40:
        st.error("Bias Alert – Fairness Audit Required")