# -*- coding: utf-8 -*-
"""overview

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6CBWXjwveQALQIuGmHdHJDrNm6JE2aQ
"""

import streamlit as st


def render():
    st.markdown("""
<style>
.hero {
    background: linear-gradient(135deg, #1f4e79 0%, #0d1b2a 100%);
    padding: 50px 40px;
    border-radius: 18px;
    color: white;
    margin-bottom: 30px;
}

.hero h1 {
    font-size: 42px;
    margin-bottom: 10px;
}

.hero p {
    font-size: 18px;
    opacity: 0.9;
}
</style>

<div class="hero">
    <h1>India AI Governance Playbook</h1>
    <p>
    Operationalizing the National AI Governance Framework into structured,
    lifecycle-aligned, cross-framework intelligence workflows.
    </p>
</div>
""", unsafe_allow_html=True)
    st.header("Overview")

    st.markdown("""
    ### Purpose
    This Playbook operationalizes the India AI Governance Framework 2025–26 into structured, executable governance workflows. It translates high-level policy principles into practical lifecycle controls covering governance, risk classification, data protection, secure development, evaluation, deployment, monitoring, incident response, and assurance. Designed for enterprise and public-sector adoption, it enables organizations to implement responsible, transparent, and accountable AI systems aligned with constitutional safeguards, regulatory mandates, and global best practices.

    ### Audience
    - Board & Apex Leadership
    - Chief AI Risk Officer (CARO)
    - AI Risk & Ethics Committee (AIREC)
    - Model Owners
    - Compliance Teams

    ### Scope
    This Playbook applies to all AI systems across their full lifecycle: 
    Plan → Design → Build → Evaluate → Deploy → Monitor → Respond → Assure. 
    It covers both internal and externally facing AI deployments, including high-risk systems requiring enhanced oversight. The scope includes governance structures, compliance with the DPDP Act, CERT-In reporting readiness, ISO 42001 alignment, fairness evaluation, security controls, and continuous monitoring to ensure sustainable, risk-proportionate AI governance.
    """)

    st.info("This structure mirrors international AI RMF playbook standards, localized for India.")
