# -*- coding: utf-8 -*-
"""overview

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6CBWXjwveQALQIuGmHdHJDrNm6JE2aQ
"""

import streamlit as st

def render():
    st.header("📘 Overview")

    st.markdown("""
    ### Purpose
    This Playbook operationalizes the India AI Governance Framework into executable governance workflows.

    ### Audience
    - Board & Apex Leadership
    - Chief AI Risk Officer (CARO)
    - AI Risk & Ethics Committee (AIREC)
    - Model Owners
    - Compliance Teams

    ### Scope
    Applies to all AI systems across lifecycle stages:
    Plan → Design → Build → Evaluate → Deploy → Monitor → Respond → Assure
    """)

    st.info("This structure mirrors international AI RMF playbook standards, localized for India.")