# -*- coding: utf-8 -*-
"""plan_govern

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6CBWXjwveQALQIuGmHdHJDrNm6JE2aQ
"""

import streamlit as st
import pandas as pd

def render():
    st.header("🏛 Plan & Govern")

    st.subheader("Key Tasks")
    tasks = [
        "Appoint CARO",
        "Constitute AIREC",
        "Define Risk Appetite",
        "Create AI Inventory",
        "Approve Prohibited Use Cases"
    ]

    for task in tasks:
        st.checkbox(task)

    st.subheader("Roles & Responsibilities")
    data = {
        "Role": ["Board", "CARO", "AIREC", "Model Owner"],
        "Primary Responsibility": [
            "Approve governance charter",
            "AI risk ownership",
            "High-risk approvals",
            "Operational management"
        ]
    }
    st.table(pd.DataFrame(data))

    st.success("Outcome: Governance Foundation Established")