# -*- coding: utf-8 -*-
"""reference

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6CBWXjwveQALQIuGmHdHJDrNm6JE2aQ
"""

import streamlit as st

def render():
    st.header("📄 India AI Governance Framework Reference")

    with open("assets/india_ai_framework.pdf", "rb") as pdf_file:
        st.download_button(
            label="Download Framework PDF",
            data=pdf_file,
            file_name="India_AI_Governance_Framework.pdf",
            mime="application/pdf"
        )