# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6CBWXjwveQALQIuGmHdHJDrNm6JE2aQ
"""

import streamlit as st

from modules import overview
from modules import control_catalog
import modules.cross_framework_mapping as cross_framework_mapping
from modules import plan_govern
from modules import define_design
from modules import develop_train
from modules import evaluate
from modules import deploy
from modules import monitor
from modules import respond_improve
from modules import assure_audit
from modules import downloads
from modules import reference

st.set_page_config(
    page_title="India AI Governance Playbook",
    layout="wide"
)

st.markdown("""
    <style>
        .stExpander {
            border-radius: 10px;
            border: 1px solid #e6e6e6;
            background-color: #f9fbfd;
        }
        .stButton>button {
            border-radius: 8px;
        }
    </style>
""", unsafe_allow_html=True)


with st.sidebar:

    st.markdown("## India AI Governance Playbook")
    st.markdown("Playbook is aligned with National AI Governance Framework India")
    st.markdown("---")
    menu = st.sidebar.radio(
    "Playbook Navigation",
    [
        "Overview",
        "Control Catalog",
        "Cross-Framework Mapping",
        "Plan & Govern",
        "Define & Design",
        "Develop & Train",
        "Evaluate",
        "Deploy",
        "Monitor",
        "Respond & Improve",
        "Assure & Audit",
        "Download Artifacts",
        "Framework Reference"
    ]
)


if menu == "Overview":
    overview.render()

elif menu == "Control Catalog":
    control_catalog.render()

elif menu == "Cross-Framework Mapping":
    cross_framework_mapping.render()

elif menu == "Plan & Govern":
    plan_govern.render()

elif menu == "Define & Design":
    define_design.render()

elif menu == "Develop & Train":
    develop_train.render()

elif menu == "Evaluate":
    evaluate.render()

elif menu == "Deploy":
    deploy.render()

elif menu == "Monitor":
    monitor.render()

elif menu == "Respond & Improve":
    respond_improve.render()

elif menu == "Assure & Audit":
    assure_audit.render()

elif menu == "Download Artifacts":
    downloads.render()

elif menu == "Framework Reference":
    reference.render()
